#!/bin/sh

# Usage:
#
# All commits on current branch, ever:
#   git-thanks
#
# All commits on master, ever:
#   git-thanks master
#
# All commits on master since the 0.9.0 tag:
#   git-thanks 0.9.0..master

# Adapted from https://github.com/rtomayko/dotfiles/raw/rtomayko/bin/git-thanks

git log $1 |
  grep Author: |
  sed 's/Author: \(.*\)$/\1/' |
  sort |
  uniq -c |
  sort -rn |
  sed 's/ *\([0-9]\{1,\}\) \(.*\)/\2 (\1)/'

