#!/bin/bash -eu

set -o pipefail

VBoxManage list vms
VBoxManage list runningvms | awk '{print $2}' | xargs -I vmid VBoxManage controlvm vmid poweroff
VBoxManage list vms | awk '{print $2}' | xargs -I vmid VBoxManage unregistervm --delete vmid
