#!/bin/bash -e

#
# Turn on/off VGA output
#

resolution=${2:-1920x1080}

case "$1" in
    on) xrandr --output LVDS1 --mode 1024x600 --output VGA1 --mode $resolution --right-of LVDS1;;
    off) xrandr --output VGA1 --off;;
    *) echo "vga on|off"
esac

